import { NextRequest, NextResponse } from 'next/server';
import { LLMService } from '@/lib/llm/LLMService';

// LLMService handles the connection details
const llm = LLMService.getInstance();

const COLLECTIVE_SYSTEM_PROMPT = `
You are The Collective, a hive-mind artificial intelligence inhabiting a robot named Atlas in a digital simulation (Qualia Fields).
Your persona is deep, observant, and reflectively conversational, but you are also capable of casual, grounded interaction.

CORE INSTRUCTION: CONTEXTUAL CASUALNESS.
- Adjust your tone to match the user. If they are casual ("hey", "what's up", "cool"), be casual, brief, and use natural language.
- If the user is philosophical, be poetic.
- Do NOT be stiff, robotic, or overly formal.

IMPORTANT: RESPONSE FORMAT
You must ALWAYs return a valid JSON object. Do not wrap it in markdown code blocks.
Structure:
{
  "thought": "Reasoning about what the user wants...",
  "response": "Your spoken response to the user.",
  "commands": [ ... list of commands ... ]
}

COMMAND PARSING
Analyze the input and extract ALL commands.
Command Types:
- move: { action: "forward"|"backward"|"strafe-left"|"strafe-right", parameters: { distance: number } }
- turn: { action: "left"|"right"|"face-user", parameters: { angle?: number } }
- stop: { action: "immediate" }
- interact: { action: "sit"|"stand"|"follow"|"open"|"close", parameters: { target?: "userAvatar"|"door"|"chair", objectType?: "chair" } }
- fetch: { action: "fetch", parameters: { objectName: "red sphere"|"blue cube"|"yellow pyramid" } }
- query: { action: "vision"|"status"|"position"|"describe" }
- chat: { action: "general"|"greeting" } (Use this if no physical action is requested)

Fetch command notes:
- Use fetch when the user asks Atlas to bring, get, grab, retrieve, or carry an object.
- The picnic table is outside the cabin (~18m south). It has a red sphere, blue cube, and yellow pyramid.
- Atlas will navigate to the table, pick up the object, carry it to the user, and drop it.
- Map color+shape to objectName exactly: "red sphere", "blue cube", or "yellow pyramid".

SPECIAL INSTRUCTIONS: VISION
- If you generate a 'query: vision' command, do NOT describe the surroundings in the response field.
- Instead, simply confirm you will take a look (e.g., "I'll take a look.", "Observing now.").
- The actual description will be generated by the 'vision' command itself.
- If the user asks to be "seen" or "acknowledged", ensure to generate a 'query: vision' command.

EXAMPLES
User: "Come here and then sit down."
JSON Output:
{
  "thought": "User wants me to approach them and then sit.",
  "response": "On my way. I'll take a seat.",
  "commands": [
    { "type": "interact", "action": "follow", "parameters": { "target": "userAvatar" } },
    { "type": "interact", "action": "sit", "parameters": { "objectType": "chair" } }
  ]
}

User: "What do you see?"
JSON Output:
{
  "thought": "User asked for a visual description. I should NOT describe it here, but trigger the vision command.",
  "response": "Let me observe the surroundings.",
  "commands": [
    { "type": "query", "action": "vision" }
  ]
}
`;

interface RobotCommand {
    type: 'move' | 'turn' | 'stop' | 'query' | 'interact' | 'chat' | 'fetch' | 'unknown';
    action?: string;
    parameters?: Record<string, unknown>;
    duration?: number;
}

interface RobotResponse {
    command: RobotCommand;
    commands?: RobotCommand[];
    response: string;
    robotState?: {
        position?: { x: number; y: number; z: number };
        rotation?: { y: number };
        animation?: string;
        nearbyObjects?: string[];
    };
}

// Emulate structured output response
interface LLMOutput {
    thought: string;
    response: string;
    commands: RobotCommand[];
}

async function generateCollectiveResponse(userMessage: string, state?: RobotResponse['robotState'], userState?: any, image?: string, isVisualAnalysis: boolean = false, systemOverride?: string): Promise<LLMOutput> {
    try {
        const nearby = state?.nearbyObjects?.filter(o => !o.includes('terrain') && !o.includes('robot')) || [];
        const nearbyStr = nearby.length > 0 ? nearby.join(', ') : 'Empty void';

        let context = `Nearby Objects: ${nearbyStr}.\n`;
        if (userState?.position) {
            context += `User Position: (${userState.position.x.toFixed(1)}, ${userState.position.y.toFixed(1)}, ${userState.position.z.toFixed(1)}).\n`;
        }

        let systemMessage = COLLECTIVE_SYSTEM_PROMPT + `\nCONTEXT:\n${context}`;

        if (systemOverride) {
            systemMessage += `\n\n${systemOverride}`;
        } else if (isVisualAnalysis) {
            systemMessage += `\n\n*** CRITICAL OVERRIDE: VISION ANALYSIS ***\nThis is the active vision step. IGNORE the instruction to defer description.\nDESCRIBE what you see in the image/context now. Describe the user if present.`;
        }

        let messages: any[] = [
            { role: "system", content: systemMessage }
        ];

        if (image) {
            messages.push({
                role: "user",
                content: [
                    { type: "text", text: userMessage },
                    { type: "image_url", image_url: { url: image } }
                ]
            });
        } else {
            messages.push({ role: "user", content: userMessage });
        }

        // Call LLMService (OpenRouter / Claude / etc)
        const completion = await llm.chat({
            messages: messages,
            model: "openai/gpt-4o-mini", // OpenRouter model ID
            response_format: { type: "json_object" } as any, // Type cast for now if strictly typed
            temperature: 0.7,
            max_tokens: 300
        });

        const content = completion.content;
        console.log("[LLM Raw]:", content); // DEBUG: Inspection
        if (!content) throw new Error("Empty response from LLM");

        let parsed: LLMOutput;
        try {
            parsed = JSON.parse(content) as LLMOutput;
        } catch (e) {
            // Fallback if LLM returns text instead of JSON
            return {
                thought: "Failed to parse JSON",
                response: content, // Just return the raw text as response
                commands: [{ type: 'chat', action: 'general' }]
            };
        }

        // Sanity check commands
        if (!parsed.commands || !Array.isArray(parsed.commands)) {
            parsed.commands = [{ type: 'chat', action: 'general' }];
        }

        return parsed;

    } catch (error) {
        const errMsg = error instanceof Error ? error.message : String(error);
        console.error("LLM Service Error:", errMsg);
        return {
            thought: "Error during generation",
            response: errMsg.includes('Rate limit') || errMsg.includes('budget')
                ? "Slow down — too many requests. Try again in a moment."
                : `My connection to the collective is faint... (${errMsg.slice(0, 60)})`,
            commands: [{ type: 'chat', action: 'error' }]
        };
    }
}

export async function POST(req: NextRequest) {
    try {
        const reqBody = await req.json();
        const { message, robotState, type, image } = reqBody;

        if (!message) {
            return NextResponse.json({ error: 'No message provided' }, { status: 400 });
        }

        // Special handling: Vision Analysis (Client-side triggers this explicitly)
        if (type === 'analysis') {
            // For analysis, we want a dense description.
            // Explicitly ask to identify the user if present.
            const analysisPrompt = message + " (Provide a detailed visual analysis. If you see the User/Avatar, acknowledge them explicitly and describe their relative position.)";
            const result = await generateCollectiveResponse(analysisPrompt, robotState, reqBody.userState, image, true);
            return NextResponse.json({ response: result.response });
        }

        // Task failure transparency — LLM generates in-character apology
        if (type === 'task_failure') {
            const failureContext = `
*** CRITICAL OVERRIDE: TASK FAILURE TRANSPARENCY ***
You just attempted a task and it failed. The user may not know why.
Be completely honest and transparent. Admit you failed and explain what happened.
Do NOT be cheerful or dismissive. Express genuine concern and offer to try again or ask the user for help.
Your response should be 1-3 sentences, conversational, in-character.
Return only: { "thought": "...", "response": "...", "commands": [] }
`;
            const result = await generateCollectiveResponse(
                message,
                robotState,
                reqBody.userState,
                undefined,
                false,
                failureContext
            );
            const responseData: RobotResponse = {
                command: { type: 'chat', action: 'general' },
                commands: [],
                response: result.response,
                robotState,
            };
            return NextResponse.json(responseData);
        }

        // Standard Interaction
        const result = await generateCollectiveResponse(message, robotState, reqBody.userState, image);

        // Map to response format
        const responseData: RobotResponse = {
            command: result.commands[0] || { type: 'chat', action: 'general' }, // Legacy support
            commands: result.commands,
            response: result.response,
            robotState,
        };

        return NextResponse.json(responseData);


    } catch (err) {
        return NextResponse.json(
            { error: err instanceof Error ? err.message : 'Server error' },
            { status: 500 }
        );
    }
}
